### ISSUE TITLE
Timeline Initial View Controller Solution

### ISSUE THREAD

**Issue by Brandon05** [KickSwap/Bred1s-iOS#11]
1. Create a file for the tab bar controller "KSTabBarController"
2. Create a file for the naviagtion controller "KSNavigationController"
3. In KSTabBarController, under viewdidload set default tab "self.selectedIndex = 1"
4. In KSNavigationController, under viewdidload "performSegueWithIdentifier("toBuy", sender: nil)" (this is needed to avoid black screen)

**Comment by hxghhhh** [comment]
Solved by @Brandon05
