### ISSUE TITLE
Week 9 - Review Our App

### ISSUE THREAD

**Issue by hxghhhh** [KickSwap/Bred1s-iOS#22]
We have completed 66% of the required functionality of our app. Parts of our app use the camera so testing on a simulator will cause the app to crash. Also, we were wondering what tools we can use to create GIFs of our app running on our actual device. Thanks! /cc @codepathreview

**Comment by minhkhang1795** [comment]
:+1: Nice work on the second implementation sprint! Your required user stories are almost completed. There's one week left to complete all of the required stories, add some extra optional functionalities and polish UI design. (Your app looks very cool btw)
Excited to see your progress next week!
