### ISSUE TITLE
Week 6 - Wireframes

### ISSUE THREAD

**Issue by egs104** [KickSwap/Bred1s-iOS#3]
Our hand-drawn wireframes can be found in the wireframes folder of our repo. We also made a couple of better quality mockups of some of our screens for us to get an idea of what we want to aim for, and they can be found in the mockups folder of our repo. /cc @codepathreview

**Comment by minhkhang1795** [comment]
:+1: Nice job on the wireframes! Wireframing is a common practice when building apps as it lets you create a blueprint for the app before writing any code. Having a really good blueprint that you can refer to throughout the rest of the project is a really valuable resource and will make it much easier to split up work across your team.

With the wireframes in hand, you should have a good idea of what your app will look like when you finish the project. Next week we'll jump into the data schema.
